### ISSUE TITLE
Паджинация в waste/components/binstable.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#29]
Сделать так, чтобы паджинация показывалась только если данных в таблице больше, чем помещается на страничку, и выглядела следующий образом:

**1** 2 3 4 ... 30 →

← 1 2 **3** 4 ... 30 →

← 1 ... **15** ... 30 →

← 1  ... 27 28 29 **30**

Файл src/waste/components/binstable.vue

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил встроенную в vuetify пагинацию, внешне она отличается от предыдущей, зато работает как ты описываешь. Если нужно - можно набросать стили, чтобы выглядела как старая.
https://vuetifyjs.com/en/components/data-tables#example-paginate

**Comment by vvzvlad** [comment]
да, я вот ее не хотел ставить, потому что она огромная. Ок, пусть пока будет. работает.

**Comment by nismangulov** [comment]
@vvzvlad 

То, что огромная - не проблема, можно поправить стили и сделать меньше. Главное - чтобы работала как нужно )
