### ISSUE TITLE
Выделенный маркер меняет цвет в waste/сontainers.vue 

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#30]
На страничке с мусорными контейнерами при нажатии на страничку или на маркер, маркер должен менять цвет, показывая, что он в данный момент выделен(как строка таблицы).
Файл waste/сontainers.vue

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал активные маркеры, но с одним но - в leaflet нет встроенной иконки активного маркера, поэтому пришлось найти в гугле другую векторную иконку, перекрасить и подключить её 
![image](https://user-images.githubusercontent.com/6184888/41847591-4aa1ced2-789c-11e8-8fc6-bdfc2d3b6ade.png)

**Comment by vvzvlad** [comment]
Да, работает. Но обнаружил странное поведение: https://github.com/vvzvlad/glue_user_app/issues/37
