### ISSUE TITLE
Обрезка картинки видео-трансляции в dashboard.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#31]
В карточке video в dashboard вставлена картинка с видео-камеры. Необходимо, чтобы она занимала всю площать карточки, обрезаясь по углам, а название карточки(текст Video и иконка) располагались на видео

**Comment by nismangulov** [comment]
@vvzvlad 

Задал картинку с камеры фоновым изображением, теперь карточка выглядит именно так, как ты описываешь

**Comment by vvzvlad** [comment]
работает
