### ISSUE TITLE
Рандомно меняющиеся значения в dashboard.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#32]
В dashboard на карточках есть цифровые значения, которые должны в фоном режиме каждую секунду менять свое значение на +-5% от предыдущего значения. Меняются все, кроме air и weather

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил рандомизацию значений в дашборде. Ещё не стал делать рандомизацию в количестве инцидентов в электроснабжении - оно бы выглядело очень странно.

Ещё по формуле расчета - а точно нужно +-5% именно от предыдущего значения? От базового значения и считать проще, и если работать с предыдущим значением - оно может уплыть очень далеко от базового через некоторое время.

**Comment by vvzvlad** [comment]
Да, работает. По формуле — пусть будут как есть, если понадобится, я поправлю. Это не критично.
