### ISSUE TITLE
Тепловая карта в eco_monitoring/map.vue 

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#33]
В файле eco_monitoring/map.vue  надо разместить несколько очагов тепловой карты так, чтобы они покрывали большинство площади москвы.

**Comment by nismangulov** [comment]
@vvzvlad 

Пока разбирался, как сделать тепловую карту - оказалось, ни один плагин для них не работает с Vue2Leaflet, нашей компонентой для карт. Пришлось брать самую популярную библиотеку для тепловых карт и разбираться, как сделать враппер для неё, чтобы оно корректно работало с нашими картами.

В итоге, сделал враппер для тепловых карт, подключил их и сделал несколько рандомных точек с рандомным радиусом, чтобы примерно покрывали большую часть площади Москвы.

Если нужны какие-то настройки тепловой карты, то опции хранятся в массиве heatmapOptions, а данные - в heatmapData. Сами опции можно подсмотреть в доке по heatmap.js https://www.patrick-wied.at/static/heatmapjs/docs.html

![image](https://user-images.githubusercontent.com/6184888/41896074-7c004194-7945-11e8-8a66-464e85b540d5.png)

**Comment by vvzvlad** [comment]
работает
