### ISSUE TITLE
Кнопки "построить маршрут" и "сбросить" в waste/planning.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#34]
Кнопка "Build route" должна показывать на карте polyline, а кнопка "Clear route" — скрывать ее. Состояние при загрузке страницы — линия скрыта.

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил две кнопки - Build route и Clear route. Первая показывает полилинию, а вторая - скрывает её. По умолчанию полилиния скрыта.

**Comment by vvzvlad** [comment]
Работает
