### ISSUE TITLE
Полупрозрачные графики на фоне плашек в dashboard

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#55]
На фоне каждой плашки необходимо разместить bar chart график, подобный тому, что в waste/containters. График должен быть полупрозрачным и не перекрывать надписи на плашке

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил полупрозрачные графики (с opacity: 0.5, можно потом поправить) на карточки дашборда. Ещё доработал респонзив, чтобы они выглядели лучше и сделал скрытие текста на шкалах, если места слишком мало, чтобы он не наслаивался друг на друга.

**Comment by vvzvlad** [comment]
работает
