### ISSUE TITLE
Фоновые графики

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#57]
1)График по горизонтали должен растягиваться до размера карточки(увеличивая ширину колонок)
2)График должен прилепляться к нижней границе карточки
3)На графиках для дашборда не должно быть ни текста, ни осей.

**Comment by nismangulov** [comment]
@vvzvlad 

> 1)График по горизонтали должен растягиваться до размера карточки(увеличивая ширину колонок)

Сделал растягивание и по ширине, и по высоте. Так намного проще работать с респонзивом, но если не ок - давай переделаем.

> 2)График должен прилепляться к нижней границе карточки

Это ок, сделал

> 3)На графиках для дашборда не должно быть ни текста, ни осей.

Текст убрал, с линиями осей ещё разбираюсь

**Comment by nismangulov** [comment]
@vvzvlad 

Залил еще один коммит, теперь все ок, линии осей теперь тоже скрываются

**Comment by vvzvlad** [comment]
Работает.
