### ISSUE TITLE
Отступы у графиков

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#61]
Надо сделать минимальные отступы по бокам у графиков.
![image](https://user-images.githubusercontent.com/3315944/42757846-22184fc6-890a-11e8-9b32-1cda7f01e7b0.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Vuetify очень странно рендерит карточки, из-за чего мои чарты ошибаются с автоопределением размеров. Сейчас сделал повторный пересчет размеров после рендеринга, стало лучше

**Comment by vvzvlad** [comment]
Работает
