### ISSUE TITLE
Парковки

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#62]
1)Вынести данные в отдельный файл(по образцу waste/containers)
2)Вместо двух синих плашек разместить таблицу с парковками(тоже по образцу waste/containers)
3)Вместо 2 зеленых плашек разместить donut-charts со статистикой:
- Общее количество занятых/свободных мест(считается проходом по всем парковкам)
- Количество парковок, занятных на 20% и меньше, на 70% и меньше, на больше, чем 70%
4)Вместо последней зеленой плашки разместить bar chart с рандомными данными.

**Comment by nismangulov** [comment]
@vvzvlad 

Создал PR с апдейтом

**Comment by vvzvlad** [comment]
Работает. А сделай так, чтобы при выделении контур парковки менял цвет?

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал смену цвета контура, активный - жёлтый, все остальные - розовые

**Comment by vvzvlad** [comment]
Работает. 
1)Больше увеличения при переходе к парковке по нажатию на строку в таблице
2)В карточке конкретной парковки сделать текущий процент заполнения(текстом),  bar chart заполненности за прошлую неделю(без реальных данных пока, фейковый), адреса парковки(поле address)
3)Вместо "Current parking" сделать все-таки bar chart заполненности за прошлую неделю.

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал все 4 пункта, залил апдейт в пуллреквест #73

**Comment by vvzvlad** [comment]
![image](https://user-images.githubusercontent.com/3315944/42911488-cc1f363e-8af3-11e8-8291-1b847e42a521.png)

**Comment by vvzvlad** [comment]
![image](https://user-images.githubusercontent.com/3315944/42911508-eff6fdc6-8af3-11e8-8519-cacd6d6b0f4b.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Поправил, создал новый пуллреквест

**Comment by vvzvlad** [comment]
И все равно. 
![image](https://user-images.githubusercontent.com/3315944/42935602-b1bd754e-8b52-11e8-90f0-6517dacdea1f.png)

**Comment by vvzvlad** [comment]
А теперь исчезла граница в waste/containters — внутренняя часть страницы вплотную к краям

**Comment by nismangulov** [comment]
@vvzvlad 

Отключил скролл таблиц, теперь строки корректно схлопываются, если не влезают в клетку.

**Comment by vvzvlad** [comment]
Вроде ничего не ползет.
