### ISSUE TITLE
Сделать задержку калькуляции маршрута в waste/planning

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#63]
При нажатии кнопки build route маршрут должен строится с задержкой 1-2 секунды с индикацией процесса(https://vuetifyjs.com/ru/components/progress)

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал задержку 1-2 секунды (с рандомом) перед показом маршрута, во время построения кнопка становится неактивной, а также на ней показывается лоадер. Большой прогрессбар не стал ставить, так как не нашёл, где его красиво разместить.

![image](https://user-images.githubusercontent.com/6184888/42796667-4cd0b070-89ad-11e8-8066-55059954dc61.png)

**Comment by vvzvlad** [comment]
Работает
