### ISSUE TITLE
Меню уезжает наверх 

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_user_app#69]
В некоторых ситуациях(ширине экрана) меню уезжает наверх:
![image](https://user-images.githubusercontent.com/3315944/42820377-b0e61038-89de-11e8-8c43-366c3bf1b6ef.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Починил, менюшки теперь не накладываются

**Comment by vvzvlad** [comment]
работает
